######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 17 22:37:58 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mybucks.h
FORMS += mybucks.ui
SOURCES += main.cpp mybucks.cpp
